# Generated by Django 2.0.5 on 2019-06-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfinexapi', '0002_auto_20190623_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
